#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - nano
  - wget
  - curl
  - zip
  - unzip
  - git
  - python3
  - python3-pip
  - openjdk-11-jre-headless
  - openjdk-11-jdk-headless